name: Lint Checks
on: [push]
jobs:
  ci:
    name: Lint using biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: '18'
      - name: Lint biome
        run: pnpm biome ci .
